### ISSUE TITLE
Any interest in an infix rematch combinator

### ISSUE THREAD

**Issue by MichaelXavier** [tom-pang/rematch#3]
Hey Tom,

I've been working on my HTTP mocking library and I think I've found a function that would go well in `Control.Rematch`: an infixable matcher like allOf but comes out a bit cleaner. I wanted to get your opinion on the name and the premise before I did a PR:

``` haskell
andAlso :: Matcher a -> Matcher a -> Matcher a
andAlso m m' = Matcher {
    match = match1 <&&> match2
  , description = description m ++ " and " ++ description m'
  , describeMismatch = combineMismatch
  }
  where (<&&>) = liftA2 (&&)
        describeMismatch1 = describeMismatch m
        describeMismatch2 = describeMismatch m'
        match1            = match m
        match2            = match m'
        combineMismatch x
          | match1 x && match2 x = describeMismatch1 x ++ " and " ++ describeMismatch2 x
          | match1 x             = describeMismatch1 x
          | match2 x             = describeMismatch2 x
          | otherwise            = "You've found a bug in rematch!"

```

Example:

``` haskell
betweenFiveAndTen :: Matcher Int
betweenFiveAndTen = greaterThan 5 `andAlso` lessThan 10
```

**Comment by tom-pang** [comment]
Seems reasonable. Mind renaming `<&&>`?

Also I'd like to see a spec.

Apart from that this is great, thanks!

**Comment by MichaelXavier** [comment]
Sure. I guess I'll name it andPred or something. I'll get working on adding a spec for this tonight.

**Comment by tom-pang** [comment]
Ideally I'd like to see quite a few specs, this code has a bunch of branches (I know rematch doesn't have the best coverage right now, but I don't wanna break code other people have contributed to me ;) )

**Comment by MichaelXavier** [comment]
Hmm, what other cases should I handle?
https://github.com/MichaelXavier/rematch/blob/andAlso/core/Control/Rematch/Specs.hs#L63

**Comment by tom-pang** [comment]
Seems good enough to me. Feel free to pull req!
