### ISSUE TITLE
Tests broken, release 0.2.0.0 doesn't include Control.Rematch.Specs module.

### ISSUE THREAD

**Issue by aycanirican** [tom-pang/rematch#5]
Distribution http://hackage.haskell.org/package/rematch-0.2.0.0/rematch-0.2.0.0.tar.gz doesn't include Control.Rematch.Specs module which is used by test-suite.

**Comment by peti** [comment]
Ping?

**Comment by Profpatsch** [comment]
Ping?

**Comment by tom-pang** [comment]
This project isn't maintained. I suggest you fork it under a different name.

**Comment by Profpatsch** [comment]
@tcrayford Would it be possible to indicate on hackage that there is no maintainer? One can remove oneself from the maintainer list.

**Comment by tom-pang** [comment]
I could, but that's maintenance work. I don't even have my hackage creds anymore

**Comment by Profpatsch** [comment]
I’ll contact the hackage team. It looks like you switched away from Haskell entirely, should I request all your packages to be marked as unmaintained?
